name: Periodic Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs once every hour

jobs:
  periodic_health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the live deployment URL
        run: |
          curl --fail https://fullstackopen-cicd-o6rb.onrender.com